
=head1 rdiez's Tools

This repository contains some tools that I have written over the years. I hope that you find them useful too!

I have invested some extra time into making the tools robust and giving them reasonable help texts. Please send feedback to rdiezmail-tools at yahoo.de

The tools are:

=over

=item * B<< background.sh >>

Runs the given process with a low priority and displays a visual notification when finished.

=item * B<< print-arguments-wrapper.sh >>

When writing complex shell scripts, sometimes you wonder if a particular process is getting the right arguments and the right environment variables. Just prefix a command with the name of this script, and it will dump all arguments and environment variables to the console before starting the child process.

=item * B<< pipe-to-emacs-server.sh >>

Helps you pipe the output of a shell console command to a new emacs window.

=item * B<< RotateDir.pl >>

If you keep running a process that generates a big directory tree every time (like building a compiler toolchain overnight), and you only want to keep the most recent file trees, this directory rotation tool will automatically prune the older ones for you.

=item * B<< ConvertBitmapToSourceCode.pl >>

Converts a bitmap in Portable Pixmap format (PPM) format, monochrome or RGB565, into a C++ array. RGB565 is a very popular 16-bit color depth format among small hardware devices.

=item * B<< decode-jtag-idcode.pl >>

Breaks a JTAG IDCODE up into fields as specified in IEEE standard 1149.1. Example output:

 % perl decode-jtag-idcode.pl 0x4BA00477
 Decoding of JTAG IDCODE 0x4BA00477 (1268778103, 0b01001011101000000000010001110111):
 Version:      0b0100  (0x4, 4)
 Part number:  0b1011101000000000  (0xBA00, 47616)
 Manufacturer: 0b01000111011  (0x23B, 571)  # Name: ARM Ltd.
 Leading bit:  1  # Always set to 1 according to the IEEE standard 1149.1

=item * B<< DownloadAndBuildAutotools.sh >>

Downloads, builds and installs any desired versions of the GNU autotools (autoconf + automake).

=back

Most tools are licensed under the AGPLv3, see file F<< agpl-3.0.txt >> for details.
